### ISSUE TITLE
Vue rodando numa VPS

### ISSUE THREAD

**Issue by ricardo-tek** [Ermesoml/Delphi-with-Vue.js#1]
Bacana seu artigo, eu estou com foco exatamente em romper esta barreira de migrar para alguns recursos de front-end fora do delphi. Apesar de usar o RestDW que é um componente delphi de criação de servidores muito bom, da comunidade brasileira, se você tiver interesse posso te passar alguns exemplos. Mas na parte de front end eu ainda estou com muitas dúvidas sobre como fazer deploy do Vue em servidores locais. 
Você já colocou algum app vue em uma VPS ou em uma intranet?
ricardo.darocha (skype)
ricardodarocha@outlook.com

**Comment by Ermesoml** [comment]
Olá Ricardo,

Já utilizei sim, inclusive trabalho em uma aplicação que está em produção utilizando vue.js e Delphi.
Te adicionarei no skype para tentar ajudar com suas dúvidas.
